let skeptic_chamber = [
  { type: "flatSpike", originalPos: { x: 36, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 37, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 38, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 39, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 40, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 41, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 42, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 43, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 44, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 45, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 46, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 47, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 48, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 49, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 50, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 51, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 51, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 52, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 53, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 54, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 55, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 56, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 57, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 58, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 59, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 60, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 61, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 62, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 63, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 64, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 65, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 66, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 67, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 68, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 69, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 70, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 71, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 71, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 72, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 73, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 74, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 75, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 76, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 77, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 78, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 79, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 80, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 81, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 82, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 83, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 84, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 85, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 86, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 87, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 88, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 89, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 90, y: 1 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 91, y: 1 }, rotation: 0 },

  { type: "flatSpike", originalPos: { x: 32, y: 14 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 36, y: 14 }, rotation: 0 },
  { type: "block", originalPos: { x: 32.5, y: 12 }, rotation: 0 },
  { type: "block", originalPos: { x: 33, y: 11.8 }, rotation: 0 },
  { type: "block", originalPos: { x: 34, y: 11.75 }, rotation: 0 },
  { type: "block", originalPos: { x: 35, y: 11.8 }, rotation: 0 },
  { type: "block", originalPos: { x: 35.5, y: 12 }, rotation: 0 },

  { type: "yellowPad", originalPos: { x: 6, y: 1 }, rotation: 0 },

  { type: "spike", originalPos: { x: 8, y: 1 }, rotation: 0 },
  { type: "block", originalPos: { x: 9, y: 2 }, rotation: 0 },
  { type: "block", originalPos: { x: 9, y: 1 }, rotation: 0 },

  { type: "block", originalPos: { x: 9, y: 3 }, rotation: 0 },
  { type: "block", originalPos: { x: 10, y: 3 }, rotation: 0 },
  { type: "block", originalPos: { x: 11, y: 3 }, rotation: 0 },
  { type: "block", originalPos: { x: 12, y: 3 }, rotation: 0 },
  { type: "block", originalPos: { x: 13, y: 3 }, rotation: 0 },
  { type: "yellowPad", originalPos: { x: 13, y: 4 }, rotation: 0 },
  { type: "block", originalPos: { x: 13, y: 3 }, rotation: 0 },
  { type: "block", originalPos: { x: 13, y: 2 }, rotation: 0 },
  { type: "block", originalPos: { x: 13, y: 1 }, rotation: 0 },
  { type: "spike", originalPos: { x: 14, y: 3 }, rotation: 1.5 },

  { type: "spike", originalPos: { x: 15, y: 6 }, rotation: 0.5 },
  { type: "spike", originalPos: { x: 16, y: 5 }, rotation: 1 },
  { type: "block", originalPos: { x: 16, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 17, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 18, y: 6 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 18, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 19, y: 7 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 20, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 19, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 20, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 21, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 22, y: 6 }, rotation: 0 },
  { type: "spike", originalPos: { x: 23, y: 6 }, rotation: 1.5 },
  { type: "spike", originalPos: { x: 22, y: 5 }, rotation: 1 },

  { type: "yellowPad", originalPos: { x: 21.5, y: 7 }, rotation: 0 },

  { type: "block", originalPos: { x: 26.5, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 27.8, y: 7.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 29.1, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 30.4, y: 6.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 30.4, y: 7.5 }, rotation: 0 },

  { type: "block", originalPos: { x: 35, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 36.3, y: 6.5 }, rotation: 0 },

  { type: "block", originalPos: { x: 40.5, y: 8 }, rotation: 0 },
  { type: "pinkPad", originalPos: { x: 40.5, y: 9 }, rotation: 0 },

  { type: "wavePortal", originalPos: { x: 45, y: 10 }, rotation: 0 },

  { type: "spike", originalPos: { x: 47, y: 9 }, rotation: 0 },
  { type: "block", originalPos: { x: 47, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 47, y: 7 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 48, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 48, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 46, y: 7 }, rotation: 0.5 },
  { type: "spike", originalPos: { x: 47, y: 6 }, rotation: 1 },

  { type: "block", originalPos: { x: 46, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 46, y: 13 }, rotation: 1 },
  { type: "block", originalPos: { x: 46, y: 12 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 46, y: 11 }, rotation: 1 },
  //{ type: "block", originalPos: { x: 46, y: 11 }, rotation: 1 },
  { type: "block", originalPos: { x: 47, y: 11 }, rotation: 1 },
  { type: "block", originalPos: { x: 48, y: 11 }, rotation: 1 },
  { type: "block", originalPos: { x: 49, y: 11 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 48, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 50, y: 11 }, rotation: 1 },
  { type: "block", originalPos: { x: 50, y: 10 }, rotation: 1 },

  { type: "block", originalPos: { x: 51, y: 12 }, rotation: 1 },
  { type: "block", originalPos: { x: 52, y: 13 }, rotation: 1 },
  { type: "block", originalPos: { x: 53, y: 14 }, rotation: 1 },

  { type: "spike", originalPos: { x: 49, y: 10 }, rotation: 0.5 },
  { type: "spike", originalPos: { x: 49, y: 9 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 50, y: 9 }, rotation: 1 },

  { type: "block", originalPos: { x: 49, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 50, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 51, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 52, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 52, y: 7 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 52, y: 9 }, rotation: 0 },
  { type: "block", originalPos: { x: 53, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 53, y: 8 }, rotation: 0 },

  { type: "block", originalPos: { x: 54, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 55, y: 9 }, rotation: 0 },

  { type: "spike", originalPos: { x: 55, y: 10 }, rotation: 0 },

  { type: "block", originalPos: { x: 53, y: 11 }, rotation: 1 },
  { type: "spike", originalPos: { x: 53, y: 10 }, rotation: 1 },

  { type: "spike", originalPos: { x: 55, y: 12 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 56, y: 15 }, rotation: 1 },
  { type: "block", originalPos: { x: 56, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 56, y: 13 }, rotation: 1 },
  { type: "block", originalPos: { x: 56, y: 12 }, rotation: 1 },
  { type: "spike", originalPos: { x: 56, y: 11 }, rotation: 1 },
  { type: "block", originalPos: { x: 57, y: 11 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 57, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 58, y: 10 }, rotation: 1 },
  { type: "spike", originalPos: { x: 58, y: 9 }, rotation: 1 },
  { type: "block", originalPos: { x: 59, y: 9 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 59, y: 8 }, rotation: 1 },
  { type: "block", originalPos: { x: 60, y: 8 }, rotation: 1 },
  { type: "block", originalPos: { x: 61, y: 8 }, rotation: 1 },

  { type: "spike", originalPos: { x: 60, y: 4 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 61, y: 4 }, rotation: 0 },
  { type: "block", originalPos: { x: 62, y: 5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 62, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 63, y: 5 }, rotation: 0 },

  { type: "spike", originalPos: { x: 61, y: 7 }, rotation: 1 },
  { type: "block", originalPos: { x: 61, y: 8 }, rotation: 1 },
  { type: "block", originalPos: { x: 62, y: 8 }, rotation: 1 },
  { type: "spike", originalPos: { x: 63, y: 8 }, rotation: 1.5 },

  { type: "block", originalPos: { x: 64, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 65, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 66, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 67, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 68, y: 7 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 68, y: 8 }, rotation: 0 },

  { type: "spike", originalPos: { x: 64, y: 9.5 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 65, y: 9.5 }, rotation: 1 },
  { type: "block", originalPos: { x: 66, y: 9.5 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 66, y: 8.5 }, rotation: 1 },
  { type: "spike", originalPos: { x: 67, y: 9.5 }, rotation: 1.5 },

  { type: "spike", originalPos: { x: 67, y: 11 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 68, y: 11 }, rotation: 1 },
  { type: "spike", originalPos: { x: 68, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 69, y: 11 }, rotation: 1 },
  { type: "spike", originalPos: { x: 69, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 70, y: 10 }, rotation: 1 },
  { type: "spike", originalPos: { x: 70, y: 9 }, rotation: 1 },

  { type: "spike", originalPos: { x: 64, y: 7 }, rotation: 0 },

  { type: "flatSpike", originalPos: { x: 66, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 67, y: 7 }, rotation: 0 },

  { type: "cubePortal", originalPos: { x: 69, y: 8 }, rotation: 1.5 },
  { type: "block", originalPos: { x: 69, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 70, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 71, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 72, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 73, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 74, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 75, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 76, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 77, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 78, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 79, y: 6 }, rotation: 0 },

  { type: "spike", originalPos: { x: 76.3, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 77.3, y: 7 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 77.3, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 78.3, y: 7 }, rotation: 0 },

  { type: "wavePortal", originalPos: { x: 82, y: 9 }, rotation: 0 },

  { type: "spike", originalPos: { x: 82, y: 5 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 83, y: 5 }, rotation: 0 },
  { type: "block", originalPos: { x: 83, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 84, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 84, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 84, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 85, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 86, y: 6 }, rotation: 0 },
  { type: "spike", originalPos: { x: 86, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 87, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 87, y: 7 }, rotation: 0 },
  { type: "spike", originalPos: { x: 87, y: 8 }, rotation: 0 },

  { type: "spike", originalPos: { x: 82, y: 12 }, rotation: 0 },
  { type: "block", originalPos: { x: 82, y: 11 }, rotation: 1 },
  { type: "block", originalPos: { x: 82, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 83, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 84, y: 10 }, rotation: 1 },
  { type: "block", originalPos: { x: 85, y: 10 }, rotation: 1 },
  { type: "spike", originalPos: { x: 86, y: 10 }, rotation: 1.5 },

  { type: "block", originalPos: { x: 95, y: 1 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 2 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 3 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 4 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 5 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 6 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 7 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 8 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 9 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 10 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 11 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 12 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 13 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 14 }, rotation: 0 },
  { type: "block", originalPos: { x: 95, y: 15 }, rotation: 0 },
  { type: "spike", originalPos: { x: 95, y: 16 }, rotation: 0 },

  { type: "block", originalPos: { x: 96, y: 23 }, rotation: 0 },
  { type: "block", originalPos: { x: 96, y: 22 }, rotation: 0 },
  { type: "block", originalPos: { x: 96, y: 21 }, rotation: 0 },
  { type: "block", originalPos: { x: 96, y: 20 }, rotation: 0 },
  { type: "block", originalPos: { x: 96, y: 19 }, rotation: 0 },
  { type: "block", originalPos: { x: 96, y: 18 }, rotation: 0 },
  { type: "spike", originalPos: { x: 96, y: 17 }, rotation: 1 },

  { type: "spike", originalPos: { x: 100, y: 14 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 101, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 102, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 103, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 104, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 105, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 106, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 107, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 108, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 109, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 110, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 111, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 112, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 113, y: 14 }, rotation: 1 },
  { type: "block", originalPos: { x: 114, y: 14 }, rotation: 1 },
  { type: "spike", originalPos: { x: 115, y: 14 }, rotation: 1.5 },

  { type: "spike", originalPos: { x: 100, y: 10.5 }, rotation: 0.5 },
  { type: "block", originalPos: { x: 101, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 102, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 103, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 104, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 105, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 106, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 107, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 108, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 109, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 110, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 111, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 112, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 113, y: 10.5 }, rotation: 0 },
  { type: "block", originalPos: { x: 114, y: 10.5 }, rotation: 0 },
  { type: "spike", originalPos: { x: 115, y: 10.5 }, rotation: 1.5 },

  { type: "flatSpike", originalPos: { x: 101, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 102, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 103, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 104, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 105, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 106, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 107, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 108, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 109, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 110, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 111, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 112, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 113, y: 13 }, rotation: 1 },
  { type: "flatSpike", originalPos: { x: 114, y: 13 }, rotation: 1 },

  { type: "flatSpike", originalPos: { x: 101, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 102, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 103, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 104, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 105, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 106, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 107, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 108, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 109, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 110, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 111, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 112, y: 11.5 }, rotation: 0 },
  { type: "flatSpike", originalPos: { x: 113, y: 11.5 }, rotation: 0 },
  { type: "spike", originalPos: { x: 114, y: 11.5 }, rotation: 0 },
];
